name: "FiatUconnect (Development)"
url: "https://github.com/maxarndt/FiatUconnect"
description: "Connect your FIAT (uconnect) car to Home Assistant. 🚗"
services:
  - "mqtt:want"
version: "13.0.0"
homeassistant_api: true
image: "ghcr.io/maxarndt/image-{arch}-fiat-uconnect"
slug: "fiat_uconnect_dev"
init: false
discovery:
  - "mqtt"
options:
  FiatUser: ""
  FiatPw: ""
  FiatPin: ""

  Brand: "Fiat"
  Region: "Europe"

  RefreshInterval: 2
  Debug: false
  AutoDeepRefresh: false
  AutoDeepInterval: 15

  StartDelaySeconds: 2
schema:
  FiatUser: str
  FiatPw: password
  FiatPin: password?

  Brand: list(Fiat|AlfaRomeo|Jeep|Debug)
  Region: list(Europe|US)

  RefreshInterval: int
  Debug: bool
  AutoDeepRefresh: bool
  AutoDeepInterval: int
  StartDelaySeconds: int?
arch:
  - amd64
  - armv7
